rails/config/routes.rb
StormpathSample::Application.routes.draw do

  root to: 'users#index'

  resource :session

  get 'password-reset/:sptoken' => 'password_reset_tokens#edit', as: :password_reset
  put 'password-reset/:sptoken' => 'password_reset_tokens#update', as: :update_password
  get 'password-reset' => 'password_reset_tokens#new', as: :new_password_reset
  post 'password-reset' => 'password_reset_tokens#create', as: :request_password_token

  resources :users do
    get 'verify', on: :collection
  end
end

rails/app/models/user.rb
require 'stormpath-rails'

class User < ActiveRecord::Base
  include Stormpath::Rails::Account

  attr_accessible :css_background
end

rails/app/controllers/application_controller.rb
require 'pry'
require 'pry-debugger'

class ApplicationController < ActionController::Base

  ADMIN_GROUP_NAME = "foo"

  protect_from_forgery

  helper_method :logged_in?, :current_user, :is_admin?

  def current_user
    @current_user ||= User.where(id: session[:user_id]).first
  end

  def error_message_for resource
    resource.errors[:base].join ' '
  end

  def is_admin?
    if session[:user_id] and not @is_admin
      account = Stormpath::Rails::Client.find_account current_user.stormpath_url
      @is_admin = account.groups.any? do |group|
        group.name == ADMIN_GROUP_NAME
      end
    end
  end

  def logged_in?
    !!current_user
  end

  def require_not_logged_in
    if logged_in?
      redirect_to root_path
    end
  end

  def require_login
    unless logged_in?
      redirect_to new_session_path
    end
  end
end

rails/app/controllers/password_reset_tokens_controller.rb
class PasswordResetTokensController < ApplicationController
  before_filter :set_token

  def new
    redirect_to password_reset_path(@token) if @token
  end

  def create
    begin
      User.send_password_reset_email params[:email]
      flash[:message] = 'Password reset email sent.'
      redirect_to new_session_path
    rescue Stormpath::Error => error
      flash.now[:message] = error.message
      render :new
    end
  end

  def edit
    begin
      @user = User.verify_password_reset_token @token
    rescue Stormpath::Error => error
      flash[:message] = error.message
      redirect_to new_password_reset_token_path
    end
  end

  def update
    begin
      @user = User.verify_password_reset_token @token
      if @user.update_attributes params[:user]
        flash[:message] = 'Password changed. Please log in.'
        redirect_to new_session_path
      else
        flash.now[:message] = error_message_for(@user)
        render :edit
      end
    rescue Stormpath::Error => error
      flash[:message] = error.message
      redirect_to new_password_reset_token_path
    end
  end

  private

  def set_token
    @token = params[:sptoken]
  end
end

rails/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_filter :require_not_logged_in, only: [:new, :create]

  def new
  end

  def create
    begin
      user = User.authenticate params[:username_or_email], params[:password]
      session[:user_id] = user.id
      redirect_to users_path
    rescue Stormpath::Error => error
      flash[:message] = error.message
      render :new
    end
  end

  def destroy
    @current_user = nil
    @is_admin = nil
    session[:user_id] = nil
    redirect_to new_session_path
  end
end

rails/app/controllers/users_controller.rb
require 'pry-debugger'

class UsersController < ApplicationController
  before_filter :require_login
  skip_before_filter :require_login, only: [:new, :create, :verify]

  def index
    @delete_enabled = is_admin?
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create params[:user]

    if @user.errors[:base].empty?
      flash[:message] = "Your account has been created. Depending on how you've configured your directory, you may need to check your email and verify the account before logging in."
      redirect_to new_session_path
    else
      flash[:message] = error_message_for(@user)
      render :new
    end

  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    begin
      @user = User.find(params[:id])
      if @user.update_attributes params[:user]
        flash[:message] = "The account has been updated successfully."
        redirect_to users_path
      else
        flash[:message] = error_message_for(@user)
        render :edit
      end
    end
  end

  def destroy
    @user = User.find(params[:id])

    unless @user == current_user
      @user.destroy
    else
      flash[:message] = "You can not delete your own account!"
    end

    redirect_to users_path
  end

  def verify
    begin
      User.verify_account_email params[:sptoken]
      flash[:message] = 'Your account has been verified. Please log in using your username and password'
    rescue Stormpath::Error => error
      flash[:message] = error.message
    end

    redirect_to new_session_path
  end
end

rails/app/helpers/application_helper.rb
module ApplicationHelper
end

rails/app/helpers/password_reset_tokens_helper.rb
module PasswordResetTokensHelper
end

rails/app/helpers/sessions_helper.rb
module SessionsHelper
end

rails/app/helpers/users_helper.rb
module UsersHelper
end

rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StormpathSample</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/stormpath.css">
  </head>
  <body style="background: <%= if logged_in? then current_user.css_background end %>";>
    <div class="navbar">
      <div class="navbar-inner">
        <a class="brand" href="/">Stormpath <%= if logged_in? then ">> #{current_user.username}" end %></a>
        <% if session[:user_id] %>
          <form method="post" action="/session">
            <input class="btn logout" type="submit" value="log out">
            <input type="hidden" value="DELETE" name="_method">
          </form>
        <% end %>
      </div>
    </div>
    <% if flash[:message] %>
      <div class="alert"><%= flash[:message] %></div>
    <% end %>
    <div class="page-content">
      <%= yield %>
    </div>
  </body>
</html>

rails/app/views/password_reset_tokens/edit.html.erb
<h1>Change Your Password</h1>

<%= form_for @user, :html => { :class => "form-horizontal" }, :url => update_password_path(@token) do |f| %>
  <div class="control-group">
    <%= label_tag :password, nil, class: 'control-label' %>
    <div class="controls">
      <%= f.password_field :password, :placeholder => 'Password' %>
    </div>
  </div>
  <div class="control-group">
    <div class="controls">
      <%= f.submit 'Save', :class => 'btn btn-primary' %>
    </div>
  </div>
<% end %>

rails/app/views/password_reset_tokens/new.html.erb
<h1>Password Reset</h1>

<%= form_tag request_password_token_path, method: 'post', class: 'form-horizontal' do %>
  <div class="control-group">
    <%= label_tag :email, nil, class: 'control-label' %>
    <div class="controls">
      <%= text_field_tag :email %>
    </div>
  </div>
  <div class="control-group">
    <div class="controls">
      <%= button_tag 'Send Password Reset Email', class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

rails/app/views/users/edit.html.erb
<h1>Edit Account</h1>

<%= form_for @user, :html => { :class => "form-horizontal" } do |f| %>
  <div class="control-group">
    <%= label_tag :given_name, nil, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :given_name, :placeholder => 'Given Name' %>
    </div>
  </div>
  <div class="control-group">
    <%= label_tag :surname, nil, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :surname, :placeholder => 'Surname' %>
    </div>
  </div>
  <div class="control-group">
    <%= label_tag :email, nil, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :email, :placeholder => 'Email' %>
    </div>
  </div>
  <div class="control-group">
    <%= label_tag :username, nil, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :username, :placeholder => 'Username' %>
    </div>
  </div>
  <div class="control-group">
    <%= label_tag :css_background, nil, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :css_background, :placeholder => 'CSS Background Color' %>
    </div>
  </div>
  <div class="control-group">
    <div class="controls">
      <%= f.submit 'Save', :class => 'btn btn-primary' %>
    </div>
  </div>
<% end %>

rails/app/views/users/index.html.erb
<h1>User List</h1>

<table class="table">
  <thead>
    <tr>
      <th>Email</th>
      <th>Given Name</th>
      <th>Surname</th>
    </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.email %></td>
      <td><%= user.given_name %></td>
      <td><%= user.surname %></td>
      <td>
        <%= button_to 'Edit', edit_user_path(user), :class => 'btn', :method => :get %>
      </td>
      <td>
        <%= button_to 'Remove', user, :confirm => 'Are you sure?', :method => :delete, :class => 'btn', :disabled => !!!@delete_enabled %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

rails/app/views/users/new.html.erb
<h1>Create Account</h1>

<%= form_for @user, :html => { :class => "form-horizontal" } do |f| %>
  <div class="control-group">
    <%= label_tag :given_name, nil, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :given_name, :placeholder => 'Given Name' %>
    </div>
  </div>
  <div class="control-group">
    <%= label_tag :surname, nil, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :surname, :placeholder => 'Surname' %>
    </div>
  </div>
  <div class="control-group">
    <%= label_tag :email, nil, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :email, :placeholder => 'Email' %>
    </div>
  </div>
  <div class="control-group">
    <%= label_tag :username, nil, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :username, :placeholder => 'Username' %>
    </div>
  </div>
  <div class="control-group">
    <%= label_tag :css_background, nil, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :css_background, :placeholder => 'CSS Background Color' %>
    </div>
  </div>
  <div class="control-group">
    <%= label_tag :password, nil, class: 'control-label' %>
    <div class="controls">
      <%= f.password_field :password, :placeholder => 'Password' %>
    </div>
  </div>
  <div class="control-group">
    <div class="controls">
      <%= f.submit 'Save', :class => 'btn btn-primary' %>
    </div>
  </div>
<% end %>