rails-omniauth/config/routes.rb
RailsOmniauth::Application.routes.draw do
  root :to => "sessions#new"
  match "/auth/:provider/callback" => "sessions#create"
  match "/auth/failure", to: "sessions#failure"
  resource :session
  resource :users, only: [:new, :create]
end

rails-omniauth/app/models/user.rb
require 'stormpath-rails'

class User < ActiveRecord::Base
  include Stormpath::Rails::Account

  attr_accessible :email, :password, :given_name, :surname, :username, :stormpath_url

  def self.from_omniauth(auth)
    where(stormpath_url: auth["uid"]).first_or_create
  end
end

rails-omniauth/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private

  def current_user
    @current_user ||= User.find_by_id(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

rails-omniauth/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.from_omniauth(request.env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url, notice: "Signed in"
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Signed out"
  end

  def failure
    redirect_to new_session_path, notice: "Authentication failed"
  end
end

rails-omniauth/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.create params[:user]
    if @user.errors[:base].empty?
      flash[:message] = "Your account has been created. Depending on how you've configured your directory, you may need to check your email and verify the account before logging in."
      redirect_to new_session_path
    else
      render :new
    end
  end
end

rails-omniauth/app/helpers/application_helper.rb
module ApplicationHelper
end

rails-omniauth/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Omniauth Integration Sample</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div>
  <% if current_user %>
    Signed in as: <%= current_user.email %>
    <%= link_to "Sign out", session_path, method: "delete" %>
  <% end %>
  </div>

<% flash.each do |key, value| %>
  <div class="flash <%= key %>"><%= value %></div>
<% end %>

<%= yield %>

</body>
</html>

rails-omniauth/app/views/users/new.html.erb
<h1>Create Account</h1>

<%= form_for @user do |f| %>
  <ul>
    <li>
      <%= label_tag :given_name %>
      <%= f.text_field :given_name, :placeholder => 'Given Name' %>
    </li>
    <li>
      <%= label_tag :surname %>
      <%= f.text_field :surname, :placeholder => 'Surname' %>
    </li>
    <li>
      <%= label_tag :email %>
      <%= f.text_field :email, :placeholder => 'Email' %>
    </li>
    <li>
      <%= label_tag :username %>
      <%= f.text_field :username, :placeholder => 'Username' %>
    </li>
    <li>
      <%= label_tag :password %>
      <%= f.password_field :password, :placeholder => 'Password' %>
    </li>
    <li>
      <%= f.submit 'Save' %>
    </li>
  </ul>
<% end %>